import { ArrowRight, Camera, Check, ChevronRight, Heart, LockKeyhole, Sparkles } from "lucide-react";
import Link from "next/link";

const heroPhoto = "https://images.unsplash.com/photo-1681396059172-7532b1ef8b47?auto=format&fit=crop&fm=jpg&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDI3fHx8ZW58MHx8fHx8&ixlib=rb-4.1.0&q=80&w=1800";

const steps = [
  { icon: Camera, number: "01", title: "Capture a real moment", text: "A late coffee. A small win. The sky from the train. Start with the things that are already yours." },
  { icon: Sparkles, number: "02", title: "Turn it into a reflection", text: "Inkly helps you find a few honest words for the feeling—personal, not poster-perfect." },
  { icon: Heart, number: "03", title: "Return to it privately", text: "Your memories are yours to keep. Share only when you deliberately choose to." },
];

const faqs = [
  ["Is Inkly a social network?", "No. Inkly starts private. You can choose friends or public visibility for a memory only when you want to share it."],
  ["What happens to my photo when I make a reflection?", "Inkly sends the photo or processed image data to its secure backend and AI provider to help create the reflection. Saved photos are stored privately by default."],
  ["Can I edit the reflection?", "Yes. You can review and refine generated words before you save or share them."],
  ["How do I restore a purchase?", "Open the paywall in the app and choose Restore purchases. Your store account manages billing and active subscriptions."],
];

function Wordmark() {
  return <Link href="/" className="group flex items-center gap-2.5" aria-label="Inkly home"><span className="grid size-8 place-items-center rounded-[11px] bg-amber-300 text-[#171513] shadow-[0_0_24px_rgba(251,191,36,.25)]"><span className="font-serif text-xl leading-none">i</span></span><span className="text-lg font-semibold tracking-[-0.04em] text-stone-100">Inkly</span></Link>;
}

function SiteFooter() {
  return <footer className="border-t border-white/10 bg-[#11100e]"><div className="mx-auto flex max-w-6xl flex-col gap-8 px-5 py-10 sm:px-8 md:flex-row md:items-center md:justify-between"><div><Wordmark /><p className="mt-3 max-w-sm text-sm leading-6 text-stone-400">A quieter place for the moments you want to remember.</p></div><nav aria-label="Footer" className="flex flex-wrap gap-x-6 gap-y-3 text-sm text-stone-300"><Link className="transition hover:text-amber-200" href="/privacy">Privacy</Link><Link className="transition hover:text-amber-200" href="/terms">Terms</Link><Link className="transition hover:text-amber-200" href="/support">Support</Link><Link className="transition hover:text-amber-200" href="/delete-account">Delete account</Link></nav></div></footer>;
}

export { SiteFooter, Wordmark };

export default function Home() {
  return <main className="overflow-hidden bg-[#171513] text-stone-100">
    <header className="relative z-10 mx-auto flex max-w-6xl items-center justify-between px-5 py-5 sm:px-8"><Wordmark /><nav className="hidden items-center gap-6 text-sm text-stone-300 sm:flex" aria-label="Main navigation"><a className="transition hover:text-amber-200" href="#how-it-works">How it works</a><a className="transition hover:text-amber-200" href="#privacy">Privacy</a><a className="transition hover:text-amber-200" href="#faq">FAQ</a></nav><a className="rounded-full border border-amber-200/30 bg-amber-200 px-4 py-2 text-sm font-semibold text-[#201d18] transition hover:bg-amber-100" href="mailto:support@inkly.app?subject=Inkly%20early%20access">Get early access</a></header>

    <section className="relative isolate mx-auto grid max-w-6xl gap-12 px-5 pb-20 pt-14 sm:px-8 lg:grid-cols-[1.02fr_.98fr] lg:items-center lg:pb-28 lg:pt-20"><div className="absolute -left-32 top-8 -z-10 size-[30rem] rounded-full bg-amber-300/10 blur-[110px]" /><div><p className="mb-5 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-amber-200"><span className="size-1.5 rounded-full bg-amber-300" /> A photo journal, made personal</p><h1 className="max-w-xl font-serif text-5xl leading-[.98] tracking-[-.055em] text-stone-50 sm:text-6xl lg:text-7xl">A photo journal for the moment you need to remember.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-stone-300">Capture a real moment. Turn it into a personal reflection. Keep it private—or share it intentionally.</p><div className="mt-8 flex flex-wrap items-center gap-3"><a className="inline-flex items-center gap-2 rounded-full bg-amber-200 px-5 py-3 text-sm font-semibold text-[#201d18] transition hover:bg-amber-100" href="mailto:support@inkly.app?subject=Inkly%20early%20access">Join the waitlist <ArrowRight className="size-4" /></a><a className="inline-flex items-center gap-2 px-3 py-3 text-sm font-medium text-stone-200 transition hover:text-amber-200" href="#how-it-works">See how it works <ChevronRight className="size-4" /></a></div></div><div className="relative mx-auto w-full max-w-[500px]"><div className="absolute -right-4 top-12 size-40 rounded-full bg-[#d9723e]/25 blur-3xl" /><div className="relative overflow-hidden rounded-[2rem] border border-white/15 bg-stone-900 p-3 shadow-2xl shadow-black/40"><img src={heroPhoto} alt="An open journal in soft morning light" className="aspect-[4/5] w-full rounded-[1.45rem] object-cover opacity-80" /><div className="absolute inset-x-8 bottom-8 rounded-2xl border border-white/15 bg-[#211e19]/90 p-5 shadow-xl backdrop-blur"><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-amber-200">Today&apos;s reflection</p><p className="mt-2 font-serif text-2xl leading-tight text-stone-50">“You made room for quiet. Let it stay with you.”</p><div className="mt-4 flex items-center gap-2 text-xs text-stone-300"><LockKeyhole className="size-3.5 text-amber-200" /> Private by default</div></div></div></div></section>

    <section id="how-it-works" className="bg-[#f4efe7] py-20 text-[#25211d] sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-8"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#8b5a2b]">A gentler ritual</p><div className="mt-4 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><h2 className="max-w-2xl font-serif text-4xl leading-tight tracking-[-.04em] sm:text-5xl">What happened matters. The way you hold it can, too.</h2><p className="max-w-sm text-base leading-7 text-stone-600">A small daily practice that leaves room for how things really felt.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-stone-300 bg-stone-300 md:grid-cols-3">{steps.map(({ icon: Icon, number, title, text }) => <article key={number} className="bg-[#f9f6f0] p-7 sm:p-9"><div className="flex items-start justify-between"><Icon className="size-6 text-[#b96c2c]" /><span className="text-sm font-medium text-stone-400">{number}</span></div><h3 className="mt-14 font-serif text-2xl tracking-[-.025em]">{title}</h3><p className="mt-3 leading-7 text-stone-600">{text}</p></article>)}</div></div></section>

    <section id="privacy" className="border-y border-white/10 bg-[#211e19] py-20 sm:py-28"><div className="mx-auto grid max-w-6xl gap-12 px-5 sm:px-8 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><div className="grid size-12 place-items-center rounded-2xl bg-amber-200 text-[#201d18]"><LockKeyhole className="size-6" /></div><p className="mt-7 text-xs font-semibold uppercase tracking-[.18em] text-amber-200">Privacy, without the fine print feeling</p><h2 className="mt-4 max-w-md font-serif text-4xl leading-tight tracking-[-.04em] sm:text-5xl">Your memories begin as yours alone.</h2></div><div className="grid gap-4 sm:grid-cols-2">{[["Private by default", "Saved photos are private unless you actively choose friends or public visibility."], ["Intentional sharing", "You control whether a moment is only yours, shared with friends, or public."], ["Clear AI processing", "Inkly processes selected images to create reflections—never to train a public feed."], ["Account control", "Delete your account inside the app whenever you need to. Your subscription is managed separately by your store."]].map(([title, text]) => <div key={title} className="rounded-2xl border border-white/10 bg-white/[.045] p-5"><Check className="size-4 text-amber-200" /><h3 className="mt-5 font-medium text-stone-50">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-400">{text}</p></div>)}</div></div></section>

    <section className="bg-[#f4efe7] py-20 text-[#25211d] sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#8b5a2b]">Built around the moment</p><h2 className="mt-4 font-serif text-4xl leading-tight tracking-[-.04em] sm:text-5xl">Small touches that make coming back feel good.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-3">{[["A reflection you can make your own", "Edit the words before you keep them—so the memory still sounds like you."], ["A calendar of moments", "Find the days you want to revisit without turning your life into a feed."], ["Reminders on your terms", "A gentle prompt is available when you choose it, and easy to switch off."]].map(([title, text]) => <article key={title} className="rounded-3xl bg-[#e9dfd1] p-7"><p className="text-sm font-semibold text-[#a95e24]">Inkly</p><h3 className="mt-20 font-serif text-2xl tracking-[-.025em]">{title}</h3><p className="mt-3 leading-7 text-stone-600">{text}</p></article>)}</div></div></section>

    <section id="faq" className="bg-[#171513] py-20 sm:py-28"><div className="mx-auto grid max-w-6xl gap-10 px-5 sm:px-8 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-amber-200">Questions, answered</p><h2 className="mt-4 font-serif text-4xl leading-tight tracking-[-.04em] sm:text-5xl">The important things.</h2><p className="mt-5 text-stone-400">Need a hand? <Link className="text-amber-200 underline underline-offset-4" href="/support">Visit support</Link>.</p></div><div className="divide-y divide-white/10 border-y border-white/10">{faqs.map(([question, answer]) => <details key={question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 font-medium text-stone-100"><span>{question}</span><span className="text-xl text-amber-200 transition group-open:rotate-45">+</span></summary><p className="max-w-2xl pt-3 text-sm leading-6 text-stone-400">{answer}</p></details>)}</div></div></section>

    <section className="bg-amber-200 py-16 text-[#201d18] sm:py-20"><div className="mx-auto flex max-w-6xl flex-col gap-7 px-5 sm:px-8 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.16em] text-[#8b5a2b]">Coming soon</p><h2 className="mt-3 font-serif text-4xl tracking-[-.04em] sm:text-5xl">Keep the moments that keep you.</h2></div><a className="inline-flex w-fit items-center gap-2 rounded-full bg-[#201d18] px-5 py-3 text-sm font-semibold text-amber-100 transition hover:bg-[#3a342b]" href="mailto:support@inkly.app?subject=Inkly%20early%20access">Join the waitlist <ArrowRight className="size-4" /></a></div></section>
    <SiteFooter />
  </main>;
}
